# cluster kubernetes 

resources:
  - name: kubeInt
     type: cluster
     configuration:
       integrationName: bindu_kube
       bastionHostIP: 35.236.146.1
       bastionUser: 
       bastionIntegrationName: bindu_sshKeyIntegration
      
       
pipelines:
  - name: pipe11
    steps:
      - name: testpipelines
        type: bash 
        requires:
          resources:
            - int
        execution:
          onExecute:
            - printenv
         
      - name: testpipelines1
        type: bash 
        triggeredBy:
          steps:
            - testpipelines
        execution:
          onExecute:
            - echo "hi"
            - node --version
           
